spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  datacenter: interswitch
  environment: production
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/